apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: configuration-aws-ipam
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
    version: '>=v2.3.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: XRD for provisioning AWS VPC IPAM instances, scopes, and pools.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # configuration-aws-ipam

    Provides a reusable IPAM blueprint that owns the AWS VPC IP Address Manager plus declarative pools.
  repository: ghcr.io/hops-ops/configuration-aws-ipam
  source: github.com/hops-ops/configuration-aws-ipam
