# Step 3: IPv6 private pool CIDR becomes Ready
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPCIpamPoolCidr
metadata:
  name: my-org-ipv6-private-cidr
  annotations:
    crossplane.io/composition-resource-name: ipam-pool-cidr-ipv6-private
    gotemplating.fn.crossplane.io/composition-resource-name: ipam-pool-cidr-ipv6-private
status:
  conditions:
    - type: Ready
      status: "True"
    - type: Synced
      status: "True"
  atProvider:
    id: ipam-pool-0333333333333333c_fd00:my:app::/48
    ipamPoolId: ipam-pool-0333333333333333c
    cidr: fd00:my:app::/48
