apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: ipams.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: IPAM
    plural: ipams
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        description: IPAM defines AWS VPC IP Address Manager primitives for downstream compositions.
        required:
        - spec
        properties:
          spec:
            type: object
            description: Desired state for the IPAM resources.
            required:
            - region
            - pools
            properties:
              managementPolicies:
                type: array
                description: Management operations permitted on composed resources. Use ["*"] for full management or omit Delete to orphan.
                items:
                  type: string
                  enum:
                  - "*"
                  - Create
                  - Observe
                  - Update
                  - Delete
                  - LateInitialize
                default:
                - "*"
              providerConfigRef:
                type: object
                description: Reference to the ProviderConfig for AWS API operations.
                properties:
                  kind:
                    type: string
                    description: Kind of the provider config (ProviderConfig or ClusterProviderConfig).
                    enum:
                      - ProviderConfig
                      - ClusterProviderConfig
                    default: ProviderConfig
                  name:
                    type: string
                    description: Name of the provider config.
                required:
                  - name
              externalName:
                type: string
                description: |
                  IPAM ID to adopt (e.g., ipam-0123456789abcdef0).
                  When set, Crossplane imports the existing IPAM instead of creating a new one.
              forProvider:
                type: object
                description: Override any forProvider field on the VPCIpam resource. Keys here overwrite template defaults.
                x-kubernetes-preserve-unknown-fields: true
              region:
                type: string
                description: AWS region hosting the IPAM instance.
              operatingRegions:
                type: array
                description: Additional AWS regions where the IPAM can allocate CIDRs. Region is always included.
                items:
                  type: string
              scopes:
                type: array
                description: |
                  Optional custom IPAM scopes. By default, pools use the IPAM's built-in
                  privateDefaultScope or publicDefaultScope. Define custom scopes here
                  when you need isolated scope spaces (e.g., per-team isolation).
                items:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
                      description: Unique name for the scope, referenced by pools via scopeRef.
                    externalName:
                      type: string
                      description: |
                        IPAM Scope ID to adopt (e.g., ipam-scope-0123456789abcdef0).
                        When set, Crossplane imports the existing scope instead of creating a new one.
                    description:
                      type: string
                      description: Description for the scope.
                    tags:
                      type: object
                      description: Extra AWS tags merged with the default tag map.
                      x-kubernetes-preserve-unknown-fields: true
              pools:
                type: array
                description: Declarative list of IPAM pools and CIDR assignments.
                minItems: 1
                items:
                  type: object
                  required:
                  - name
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    name:
                      type: string
                      description: Unique identifier for the pool used in downstream selectors.
                    sourcePoolRef:
                      type: string
                      description: |
                        Reference to a parent pool by name (within same IPAM).
                        Creates a child pool that allocates from the parent's CIDR space.
                        Use this for subnet pools that allocate from VPC pools.
                    externalName:
                      type: string
                      description: |
                        IPAM Pool ID to adopt (e.g., ipam-pool-0123456789abcdef0).
                        When set, Crossplane imports the existing pool instead of creating a new one.
                    managementPolicies:
                      type: array
                      description: |
                        ManagementPolicies for this pool. Overrides spec.managementPolicies if set.
                        Use to orphan specific pools on deletion while deleting others.
                      items:
                        type: string
                        enum:
                        - "*"
                        - Create
                        - Observe
                        - Update
                        - Delete
                        - LateInitialize
                    forProvider:
                      type: object
                      description: Override any forProvider field on the VPCIpamPool resource. Keys here overwrite template defaults.
                      x-kubernetes-preserve-unknown-fields: true
                    cidr:
                      type: string
                      description: |
                        Base CIDR for the pool. Conflicts with netmaskLength.
                        For IPv6 ULA pools, use netmaskLength instead to let AWS auto-assign from fd00::/8.
                    netmaskLength:
                      type: integer
                      minimum: 0
                      maximum: 128
                      description: |
                        Netmask length for auto-assigned CIDR. Conflicts with cidr.
                        Use this for IPv6 ULA pools where AWS assigns from fd00::/8 range.
                    cidrExternalName:
                      type: string
                      description: |
                        VPCIpamPoolCidr external name to adopt. Format: cidr_pool-id
                        (e.g., 10.0.0.0/8_ipam-pool-0123456789abcdef0).
                        When set, Crossplane imports the existing CIDR instead of creating a new one.
                    amazonProvidedIpv6CidrBlock:
                      type: boolean
                      description: Request Amazon-provided IPv6 CIDR block (for public IPv6 pools).
                    addressFamily:
                      type: string
                      description: Address family for this pool (ipv4 or ipv6). Defaults to ipv4.
                      enum:
                      - ipv4
                      - ipv6
                      default: ipv4
                    publicIpSource:
                      type: string
                      description: Source of public IP addresses for IPv6 pools (amazon or byoip).
                      enum:
                      - amazon
                      - byoip
                    awsService:
                      type: string
                      description: AWS service for IPv6 allocation (ec2 for VPC/EC2).
                    scope:
                      type: string
                      description: |
                        Pool scope type (private or public). Defaults to private.
                        - private: Uses IPAM's privateDefaultScope (or custom scope via scopeRef)
                        - public: Uses IPAM's publicDefaultScope (required for awsService: ec2)
                      enum:
                      - private
                      - public
                    scopeRef:
                      type: string
                      description: |
                        Reference to a custom scope defined in spec.scopes by name.
                        When set, the pool uses this custom scope instead of the IPAM's default scope.
                        Cannot be used with scope: public + awsService (public pools require AWS default scope).
                    region:
                      type: string
                      description: AWS region that owns the pool. Defaults to aws.config.region.
                    locale:
                      type: string
                      description: Locale owning the pool. Defaults to the pool region.
                    description:
                      type: string
                      description: Optional description attached to the pool.
                    allocationDefaultNetmaskLength:
                      type: integer
                      minimum: 0
                      description: Default netmask length assigned to new allocations.
                    allocationMinNetmaskLength:
                      type: integer
                      minimum: 0
                      description: Minimum netmask length allowed within the pool.
                    allocationMaxNetmaskLength:
                      type: integer
                      minimum: 0
                      description: Maximum netmask length allowed within the pool.
                    labels:
                      type: object
                      description: Labels propagated to VpcIpamPool resources so other compositions can select pools.
                      x-kubernetes-preserve-unknown-fields: true
                    tags:
                      type: object
                      description: Extra AWS tags merged with the default tag map.
                      x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            description: Observed state of the rendered IPAM resources.
            properties:
              ipam:
                type: object
                properties:
                  name:
                    type: string
                  region:
                    type: string
                  arn:
                    type: string
                  id:
                    type: string
                  privateDefaultScopeId:
                    type: string
                    description: IPAM's built-in default private scope ID.
                  publicDefaultScopeId:
                    type: string
                    description: IPAM's built-in default public scope ID.
                  pools:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        region:
                          type: string
                        locale:
                          type: string
                        id:
                          type: string
                        arn:
                          type: string
                        cidr:
                          type: string
                        allocationDefaultNetmaskLength:
                          type: integer
                        allocationMinNetmaskLength:
                          type: integer
                        allocationMaxNetmaskLength:
                          type: integer
        
