# Step 1: VPCIpam becomes Ready
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPCIpam
metadata:
  name: my-org-ipam
  annotations:
    crossplane.io/composition-resource-name: ipam
    gotemplating.fn.crossplane.io/composition-resource-name: ipam
status:
  conditions:
    - type: Ready
      status: "True"
    - type: Synced
      status: "True"
  atProvider:
    id: ipam-0123456789abcdef0
    arn: arn:aws:ec2:us-east-1:123456789012:ipam/ipam-0123456789abcdef0
    privateDefaultScopeId: ipam-scope-0123456789abcdef0
    publicDefaultScopeId: ipam-scope-0123456789abcdef1
