# IPAM with IPv4 and IPv6 pools (dual-stack)
# For single-account setups without AWS Organizations
#
# Pool types:
# - IPv4: RFC 1918 private addresses (10.0.0.0/8)
# - IPv6 ULA: Private addresses from fd00::/8 (netmaskLength, AWS auto-assigns)
# - IPv6 GUA: Amazon-provided globally routable addresses
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: IPAM
metadata:
  name: platform
  namespace: default
spec:
  providerConfigRef:
    name: default
  region: us-east-1
  operatingRegions:
    - us-east-1
  pools:
    # IPv4 global pool
    - name: ipv4
      addressFamily: ipv4
      region: us-east-1
      cidr: 10.0.0.0/8
      allocationDefaultNetmaskLength: 16
      allocationMinNetmaskLength: 12
      allocationMaxNetmaskLength: 20
      description: Global IPv4 pool
      labels:
        address-family: ipv4
        pool-type: global

    # IPv6 ULA pool (private)
    # AWS auto-assigns from fd00::/8 range
    - name: ipv6-private
      addressFamily: ipv6
      scope: private
      region: us-east-1
      locale: us-east-1
      netmaskLength: 32  # Largest ULA block AWS allows
      allocationDefaultNetmaskLength: 48
      allocationMinNetmaskLength: 40
      allocationMaxNetmaskLength: 56
      description: Global IPv6 private pool (ULA)
      labels:
        address-family: ipv6
        ipv6-type: ula
        pool-type: global

    # IPv6 GUA pool (public, Amazon-provided)
    - name: ipv6-public
      addressFamily: ipv6
      scope: public
      region: us-east-1
      locale: us-east-1
      amazonProvidedIpv6CidrBlock: true
      publicIpSource: amazon
      awsService: ec2
      netmaskLength: 52  # AWS provisions /52 GUA block
      allocationDefaultNetmaskLength: 56
      allocationMinNetmaskLength: 52
      allocationMaxNetmaskLength: 60
      description: Global IPv6 public pool (Amazon GUA)
      labels:
        address-family: ipv6
        ipv6-type: gua
        pool-type: global
