# IPAM example with IPv4 and IPv6 pools
# For single-account setups without AWS Organizations
#
# Note: AWS IPAM does NOT support IPv6 ULA (fd00::/8) CIDRs.
# For IPv6, use Amazon-provided GUA (scope: public with amazonProvidedIpv6CidrBlock)
# or BYOIP (bring your own registered IPv6 ranges).
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: IPAM
metadata:
  name: my-ipam
  namespace: default
spec:
  organizationName: my-org
  providerConfigName: default
  scope: private
  homeRegion: us-east-1
  operatingRegions:
    - us-east-1
  pools:
    # IPv4 pool - RFC 1918 private addresses are supported
    - name: ipv4
      addressFamily: ipv4
      region: us-east-1
      cidr: 10.0.0.0/8
      allocationDefaultNetmaskLength: 20
      allocationMinNetmaskLength: 16
      allocationMaxNetmaskLength: 24
      description: IPv4 pool for VPCs

    # IPv6 Public Pool (Amazon-provided GUA for EKS Auto Mode)
    # This is the recommended approach for IPv6 in AWS
    - name: ipv6-public
      addressFamily: ipv6
      scope: public
      region: us-east-1
      locale: us-east-1
      amazonProvidedIpv6CidrBlock: true
      publicIpSource: amazon
      awsService: ec2
      netmaskLength: 52  # AWS provisions /52 GUA block (16 x /56 VPC allocations)
      allocationDefaultNetmaskLength: 56
      allocationMinNetmaskLength: 52
      allocationMaxNetmaskLength: 60
      description: Public IPv6 pool (Amazon GUA)
