# IPAM testing managementPolicies cascade behavior
# Verifies: pool.managementPolicies -> global managementPolicies
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: IPAM
metadata:
  name: mgmt-policy-test
  namespace: infra
spec:
  region: us-east-1
  pools:
    # Pool A: Explicit Observe policy
    - name: pool-a
      cidr: "10.0.0.0/16"
      managementPolicies: ["Observe"]

    # Pool B: Explicit full management
    - name: pool-b
      cidr: "10.1.0.0/16"
      managementPolicies: ["*"]

    # Pool C: No explicit policies - gets global default ["*"]
    - name: pool-c
      cidr: "10.2.0.0/16"
