# IPAM with global pool and regional child pools
# Demonstrates the recommended hierarchical architecture:
# - Global pool at top (/8)
# - Regional pools as children (using sourcePoolRef)
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: IPAM
metadata:
  name: workloads
  namespace: example-env
spec:
  providerConfigRef:
    name: hops-shared-services
  region: us-east-1
  operatingRegions:
    - us-east-1
    - us-west-2
  pools:
    # Global pool - top of hierarchy
    - name: global
      cidr: 10.0.0.0/8
      allocationDefaultNetmaskLength: 12
      allocationMinNetmaskLength: 10
      allocationMaxNetmaskLength: 16
      description: Global IPv4 pool
      labels:
        pool-type: global
        hops.ops.com.ai/global-pool: ipv4

    # Regional pool for us-east-1 (child of global)
    - name: workloads-east
      sourcePoolRef: global
      region: us-east-1
      locale: us-east-1
      cidr: 10.0.0.0/12
      allocationDefaultNetmaskLength: 16
      allocationMinNetmaskLength: 16
      allocationMaxNetmaskLength: 20
      description: Regional pool for us-east-1
      labels:
        pool-type: regional
        region: us-east-1
        hops.ops.com.ai/regional-pool: us-east-1

    # Regional pool for us-west-2 (child of global)
    - name: workloads-west
      sourcePoolRef: global
      region: us-west-2
      locale: us-west-2
      cidr: 10.16.0.0/12
      allocationDefaultNetmaskLength: 16
      allocationMinNetmaskLength: 16
      allocationMaxNetmaskLength: 20
      description: Regional pool for us-west-2
      labels:
        pool-type: regional
        region: us-west-2
        hops.ops.com.ai/regional-pool: us-west-2
