# IPAM with manual child subnet pool (sourcePoolRef pattern)
# Creates a VPC pool and a child subnet pool using explicit sourcePoolRef
#
# This is the manual approach - for the simpler automatic approach,
# see example-with-auto-subnet-pool.yaml
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: IPAM
metadata:
  name: platform
  namespace: infra
spec:
  scope: private
  homeRegion: us-east-1
  pools:
    # Parent pool for VPC allocations
    - name: vpc-pool
      cidr: "10.0.0.0/8"
      allocationDefaultNetmaskLength: 16
      allocationMinNetmaskLength: 16
      allocationMaxNetmaskLength: 20
      labels:
        hops.ops.com.ai/global-pool: sandbox
    # Child pool for subnet allocations (explicit sourcePoolRef)
    - name: subnet-pool
      sourcePoolRef: vpc-pool
      allocationDefaultNetmaskLength: 24
      allocationMinNetmaskLength: 20
      allocationMaxNetmaskLength: 28
      labels:
        hops.ops.com.ai/global-pool: sandbox-subnets
